// ===== 成分数据库 — 80+ 条目 =====
// 安全等级: 1=高风险 2=中风险 3=一般 4=安全 5=非常安全

export interface IngredientInfo {
  name: string;
  nameEn: string;
  aliases: string[];
  category: string;
  safety: 1 | 2 | 3 | 4 | 5;
  functions: string[];
  description: string;
  concerns: string[];
  goodFor: string[];
  badFor: string[];
  avoidWith: string[];
}

export const INGREDIENT_DB: IngredientInfo[] = [
  // ===== 保湿 =====
  {
    name: "透明质酸",
    nameEn: "Hyaluronic Acid",
    aliases: ["玻尿酸", "HA", "sodium hyaluronate", "透明质酸钠"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "锁水", "抗皱"],
    description: "天然保湿因子，能吸收自身重量1000倍的水分",
    concerns: [],
    goodFor: ["所有肤质", "干性肌肤", "敏感肌"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "甘油",
    nameEn: "Glycerin",
    aliases: ["丙三醇", "glycerol"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "柔润"],
    description: "经典保湿成分，从空气中吸收水分保持皮肤湿润",
    concerns: ["高浓度在干燥环境下可能反吸皮肤水分"],
    goodFor: ["所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "角鲨烷",
    nameEn: "Squalane",
    aliases: ["鲨烷", "角鲨烯"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "修护屏障", "抗氧化"],
    description: "模拟皮脂成分，亲肤性极佳，形成保护膜锁水",
    concerns: [],
    goodFor: ["干性肌肤", "敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "神经酰胺",
    nameEn: "Ceramide",
    aliases: ["分子钉", "ceramide NP", "ceramide AP", "ceramide EOP"],
    category: "保湿",
    safety: 5,
    functions: ["修护屏障", "保湿", "抗炎"],
    description: "皮肤屏障核心成分，修复受损角质层",
    concerns: [],
    goodFor: ["敏感肌", "干性肌肤", "屏障受损"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "尿素",
    nameEn: "Urea",
    aliases: ["carbamide"],
    category: "保湿",
    safety: 4,
    functions: ["保湿", "软化角质", "促渗透"],
    description: "天然保湿因子成分，低浓度保湿高浓度去角质",
    concerns: ["高浓度(>10%)有刺激性"],
    goodFor: ["干性肌肤", "粗糙肌肤"],
    badFor: ["破损皮肤"],
    avoidWith: [],
  },
  {
    name: "丁二醇",
    nameEn: "Butylene Glycol",
    aliases: ["1,3-丁二醇", "BG"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "溶剂", "促渗透"],
    description: "常用保湿溶剂，质地清爽不黏腻",
    concerns: [],
    goodFor: ["油性肌肤", "混合肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "胆固醇",
    nameEn: "Cholesterol",
    aliases: [],
    category: "保湿",
    safety: 5,
    functions: ["修护屏障", "保湿"],
    description: "与神经酰胺协同修复皮肤屏障",
    concerns: [],
    goodFor: ["敏感肌", "干性肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "海藻糖",
    nameEn: "Trehalose",
    aliases: [],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "抗氧化"],
    description: "天然糖类保湿剂，在极端环境下保护细胞",
    concerns: [],
    goodFor: ["所有肤质"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 美白 =====
  {
    name: "烟酰胺",
    nameEn: "Niacinamide",
    aliases: ["维生素B3", "VB3", "nicotinamide"],
    category: "美白",
    safety: 5,
    functions: ["美白", "控油", "抗炎", "修护屏障"],
    description: "全能型成分，抑制黑色素转运，收缩毛孔",
    concerns: ["部分人不耐受可能泛红", "建议从低浓度开始"],
    goodFor: ["油性肌肤", "暗沉肌肤", "毛孔粗大"],
    badFor: ["烟酰胺不耐受人群"],
    avoidWith: ["果酸", "水杨酸"],
  },
  {
    name: "维生素C",
    nameEn: "Ascorbic Acid",
    aliases: ["VC", "抗坏血酸", "L-抗坏血酸", "左旋维C", "左旋VC"],
    category: "美白",
    safety: 4,
    functions: ["美白", "抗氧化", "促胶原合成"],
    description: "强效抗氧化剂，抑制酪氨酸酶活性，提亮肤色",
    concerns: ["易氧化变色", "高浓度有刺激性", "需避光保存"],
    goodFor: ["暗沉肌肤", "光老化肌肤"],
    badFor: ["极度敏感肌"],
    avoidWith: ["视黄醇", "BPO"],
  },
  {
    name: "熊果苷",
    nameEn: "Arbutin",
    aliases: ["α-熊果苷", "β-熊果苷"],
    category: "美白",
    safety: 4,
    functions: ["美白", "淡斑"],
    description: "天然美白成分，温和抑制酪氨酸酶",
    concerns: ["β型纯度不够可能释放氢醌"],
    goodFor: ["色斑肌肤", "暗沉肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "传明酸",
    nameEn: "Tranexamic Acid",
    aliases: ["氨甲环酸", "凝血酸"],
    category: "美白",
    safety: 4,
    functions: ["美白", "淡斑", "抗炎"],
    description: "抑制黑色素细胞活化，改善色素沉着",
    concerns: [],
    goodFor: ["色斑肌肤", "炎症后色沉"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "曲酸",
    nameEn: "Kojic Acid",
    aliases: [],
    category: "美白",
    safety: 3,
    functions: ["美白", "淡斑"],
    description: "螯合铜离子抑制酪氨酸酶，美白效果显著",
    concerns: ["有一定刺激性", "可能致敏"],
    goodFor: ["色斑肌肤"],
    badFor: ["敏感肌"],
    avoidWith: [],
  },
  {
    name: "光甘草定",
    nameEn: "Glabridin",
    aliases: ["甘草提取物"],
    category: "美白",
    safety: 5,
    functions: ["美白", "抗炎", "抗氧化"],
    description: "甘草根提取物，温和美白兼具舒缓功效",
    concerns: [],
    goodFor: ["敏感肌", "暗沉肌肤"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 抗氧化 =====
  {
    name: "维生素E",
    nameEn: "Tocopherol",
    aliases: ["VE", "生育酚", "tocopheryl acetate"],
    category: "抗氧化",
    safety: 5,
    functions: ["抗氧化", "保湿", "修护"],
    description: "脂溶性抗氧化剂，保护细胞膜免受自由基损伤",
    concerns: [],
    goodFor: ["所有肤质", "干性肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "辅酶Q10",
    nameEn: "Ubiquinone",
    aliases: ["CoQ10", "泛醌"],
    category: "抗氧化",
    safety: 5,
    functions: ["抗氧化", "抗衰老", "提亮"],
    description: "线粒体辅酶，增强细胞能量代谢抗氧化",
    concerns: [],
    goodFor: ["熟龄肌肤", "暗沉肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "白藜芦醇",
    nameEn: "Resveratrol",
    aliases: [],
    category: "抗氧化",
    safety: 4,
    functions: ["抗氧化", "抗衰老", "抗炎"],
    description: "多酚类抗氧化剂，清除自由基延缓衰老",
    concerns: ["易氧化", "需避光"],
    goodFor: ["熟龄肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "虾青素",
    nameEn: "Astaxanthin",
    aliases: [],
    category: "抗氧化",
    safety: 5,
    functions: ["抗氧化", "抗炎", "抗光老化"],
    description: "抗氧化能力是VE的1000倍，强效对抗光老化",
    concerns: ["天然红色可能暂时染色"],
    goodFor: ["光老化肌肤", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "阿魏酸",
    nameEn: "Ferulic Acid",
    aliases: [],
    category: "抗氧化",
    safety: 4,
    functions: ["抗氧化", "增效VC/VE", "防晒辅助"],
    description: "与VC和VE组成抗氧化铁三角，增强防护效果",
    concerns: [],
    goodFor: ["光老化肌肤", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "茶多酚",
    nameEn: "Tea Polyphenols",
    aliases: ["绿茶提取物", "EGCG", "儿茶素"],
    category: "抗氧化",
    safety: 5,
    functions: ["抗氧化", "抗炎", "控油"],
    description: "绿茶中的多酚类物质，抗氧化同时控油抗炎",
    concerns: [],
    goodFor: ["油性肌肤", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 抗衰老 =====
  {
    name: "视黄醇",
    nameEn: "Retinol",
    aliases: ["A醇", "维A醇", "维生素A"],
    category: "抗衰老",
    safety: 3,
    functions: ["抗衰老", "促细胞更新", "淡纹", "控油"],
    description: "公认的抗衰金标准，促进胶原蛋白合成和细胞更新",
    concerns: ["有刺激性", "需建立耐受", "孕妇禁用", "必须夜间使用", "需配合防晒"],
    goodFor: ["熟龄肌肤", "毛孔粗大", "细纹肌肤"],
    badFor: ["敏感肌", "屏障受损", "孕妇"],
    avoidWith: ["果酸", "水杨酸", "BPO", "维生素C"],
  },
  {
    name: "视黄醛",
    nameEn: "Retinal",
    aliases: ["A醛", "维A醛"],
    category: "抗衰老",
    safety: 3,
    functions: ["抗衰老", "促细胞更新", "抗菌"],
    description: "比视黄醇更接近活性形态，效果更强但也更刺激",
    concerns: ["刺激性较强", "需建立耐受", "孕妇禁用"],
    goodFor: ["熟龄肌肤"],
    badFor: ["敏感肌", "孕妇"],
    avoidWith: ["果酸", "水杨酸", "BPO"],
  },
  {
    name: "胜肽",
    nameEn: "Peptides",
    aliases: ["多肽", "寡肽", "六胜肽", "蓝铜胜肽", "棕榈酰五肽"],
    category: "抗衰老",
    safety: 5,
    functions: ["抗衰老", "促胶原合成", "紧致"],
    description: "信号肽促进胶原蛋白合成，温和有效的抗衰成分",
    concerns: [],
    goodFor: ["熟龄肌肤", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "腺苷",
    nameEn: "Adenosine",
    aliases: [],
    category: "抗衰老",
    safety: 5,
    functions: ["抗衰老", "促胶原合成", "舒缓"],
    description: "温和抗衰成分，促进胶原蛋白合成改善细纹",
    concerns: [],
    goodFor: ["所有肤质", "熟龄肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "玻色因",
    nameEn: "Proxylane",
    aliases: ["羟丙基四氢吡喃三醇"],
    category: "抗衰老",
    safety: 5,
    functions: ["抗衰老", "促糖胺聚糖合成", "紧致"],
    description: "欧莱雅专利成分，促进真皮层糖胺聚糖合成",
    concerns: [],
    goodFor: ["熟龄肌肤", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 去角质 =====
  {
    name: "水杨酸",
    nameEn: "Salicylic Acid",
    aliases: ["BHA", "柳树皮提取物"],
    category: "去角质",
    safety: 3,
    functions: ["去角质", "清洁毛孔", "抗炎", "控油"],
    description: "脂溶性酸，深入毛孔清除油脂和角质，祛痘利器",
    concerns: ["有刺激性", "孕妇慎用", "浓度不宜超过2%"],
    goodFor: ["油性肌肤", "痘痘肌", "黑头"],
    badFor: ["干性肌肤", "敏感肌", "孕妇"],
    avoidWith: ["视黄醇", "果酸"],
  },
  {
    name: "果酸",
    nameEn: "AHA",
    aliases: ["甘醇酸", "乙醇酸", "glycolic acid", "Alpha Hydroxy Acid"],
    category: "去角质",
    safety: 3,
    functions: ["去角质", "提亮", "促细胞更新"],
    description: "水溶性酸，剥脱老废角质促进新陈代谢",
    concerns: ["光敏性增加", "需配合防晒", "有刺激性"],
    goodFor: ["暗沉肌肤", "粗糙肌肤"],
    badFor: ["敏感肌", "屏障受损"],
    avoidWith: ["视黄醇", "水杨酸", "烟酰胺", "酒精"],
  },
  {
    name: "杏仁酸",
    nameEn: "Mandelic Acid",
    aliases: [],
    category: "去角质",
    safety: 4,
    functions: ["去角质", "美白", "抗菌"],
    description: "分子量较大的果酸，渗透慢刺激小，适合入门",
    concerns: ["需配合防晒"],
    goodFor: ["敏感肌入门", "痘痘肌", "暗沉肌肤"],
    badFor: [],
    avoidWith: ["视黄醇"],
  },
  {
    name: "乳酸",
    nameEn: "Lactic Acid",
    aliases: [],
    category: "去角质",
    safety: 4,
    functions: ["去角质", "保湿", "提亮"],
    description: "温和果酸，去角质同时有保湿作用",
    concerns: ["需配合防晒"],
    goodFor: ["干性肌肤", "敏感肌入门"],
    badFor: [],
    avoidWith: ["视黄醇"],
  },
  {
    name: "壬二酸",
    nameEn: "Azelaic Acid",
    aliases: ["杜鹃花酸"],
    category: "去角质",
    safety: 4,
    functions: ["去角质", "美白", "抗炎", "抗菌"],
    description: "多功能酸类，祛痘美白抗炎三合一",
    concerns: ["初期可能有轻微刺痛"],
    goodFor: ["痘痘肌", "玫瑰痤疮", "色素沉着"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "水杨酸衍生物",
    nameEn: "Betaine Salicylate",
    aliases: ["超分子水杨酸", "辛酰水杨酸"],
    category: "去角质",
    safety: 4,
    functions: ["去角质", "清洁毛孔"],
    description: "水杨酸的温和衍生物，降低刺激性保留功效",
    concerns: [],
    goodFor: ["敏感肌", "油性肌肤"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 舒缓修护 =====
  {
    name: "积雪草提取物",
    nameEn: "Centella Asiatica Extract",
    aliases: ["CICA", "积雪草苷", "羟基积雪草苷", "马齿苋"],
    category: "舒缓修护",
    safety: 5,
    functions: ["修护", "舒缓", "抗炎", "促愈合"],
    description: "经典修护成分，促进伤口愈合和胶原合成",
    concerns: [],
    goodFor: ["敏感肌", "痘痘肌", "屏障受损"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "尿囊素",
    nameEn: "Allantoin",
    aliases: [],
    category: "舒缓修护",
    safety: 5,
    functions: ["舒缓", "修护", "保湿"],
    description: "促进细胞增殖和伤口愈合，温和舒缓",
    concerns: [],
    goodFor: ["敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "红没药醇",
    nameEn: "Bisabolol",
    aliases: ["甜没药醇"],
    category: "舒缓修护",
    safety: 5,
    functions: ["舒缓", "抗炎", "抗菌"],
    description: "洋甘菊提取物，强效抗炎舒缓成分",
    concerns: [],
    goodFor: ["敏感肌", "泛红肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "泛醇",
    nameEn: "Panthenol",
    aliases: ["维生素B5", "VB5", "D-泛醇"],
    category: "舒缓修护",
    safety: 5,
    functions: ["修护", "保湿", "舒缓"],
    description: "维生素B5前体，深层保湿修复受损皮肤",
    concerns: [],
    goodFor: ["所有肤质", "敏感肌", "屏障受损"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "芦荟提取物",
    nameEn: "Aloe Vera Extract",
    aliases: ["芦荟", "aloe barbadensis"],
    category: "舒缓修护",
    safety: 5,
    functions: ["舒缓", "保湿", "修护"],
    description: "天然舒缓保湿成分，晒后修护经典选择",
    concerns: [],
    goodFor: ["所有肤质", "晒后修护"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "甘草酸二钾",
    nameEn: "Dipotassium Glycyrrhizate",
    aliases: ["甘草提取物"],
    category: "舒缓修护",
    safety: 5,
    functions: ["舒缓", "抗炎", "抗敏"],
    description: "甘草根提取的抗炎成分，舒缓泛红刺激",
    concerns: [],
    goodFor: ["敏感肌", "泛红肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "依克多因",
    nameEn: "Ectoin",
    aliases: [],
    category: "舒缓修护",
    safety: 5,
    functions: ["修护", "抗炎", "保湿"],
    description: "嗜盐菌产生的天然保护分子，修护细胞膜",
    concerns: [],
    goodFor: ["敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 防晒 =====
  {
    name: "氧化锌",
    nameEn: "Zinc Oxide",
    aliases: [],
    category: "防晒",
    safety: 5,
    functions: ["物理防晒", "UVA/UVB防护"],
    description: "物理防晒剂，反射紫外线，温和不刺激",
    concerns: ["可能泛白", "质地较厚重"],
    goodFor: ["敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "二氧化钛",
    nameEn: "Titanium Dioxide",
    aliases: [],
    category: "防晒",
    safety: 5,
    functions: ["物理防晒", "UVB防护"],
    description: "物理防晒剂，主要防护UVB波段",
    concerns: ["可能泛白", "UVA防护较弱"],
    goodFor: ["敏感肌"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "甲氧基肉桂酸辛酯",
    nameEn: "Octinoxate",
    aliases: ["OMC", "桂皮酸盐"],
    category: "防晒",
    safety: 3,
    functions: ["化学防晒", "UVB防护"],
    description: "常用化学防晒剂，吸收UVB紫外线",
    concerns: ["可能干扰内分泌", "珊瑚礁不友好"],
    goodFor: ["非敏感肌"],
    badFor: ["敏感肌", "海洋环保关注者"],
    avoidWith: [],
  },
  {
    name: "阿伏苯宗",
    nameEn: "Avobenzone",
    aliases: ["丁基甲氧基二苯甲酰基甲烷"],
    category: "防晒",
    safety: 3,
    functions: ["化学防晒", "UVA防护"],
    description: "广谱UVA防护化学防晒剂",
    concerns: ["光稳定性差", "需配合稳定剂"],
    goodFor: ["需要UVA防护"],
    badFor: ["敏感肌"],
    avoidWith: [],
  },

  // ===== 清洁 =====
  {
    name: "氨基酸表面活性剂",
    nameEn: "Amino Acid Surfactant",
    aliases: ["椰油酰谷氨酸钠", "月桂酰谷氨酸钠", "氨基酸洁面"],
    category: "清洁",
    safety: 5,
    functions: ["温和清洁"],
    description: "pH接近皮肤的温和清洁成分，不破坏皮脂膜",
    concerns: [],
    goodFor: ["所有肤质", "敏感肌"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "SLS",
    nameEn: "Sodium Lauryl Sulfate",
    aliases: ["月桂醇硫酸酯钠", "十二烷基硫酸钠"],
    category: "清洁",
    safety: 2,
    functions: ["强力清洁", "起泡"],
    description: "强力清洁表活，去脂力强但刺激性大",
    concerns: ["刺激性强", "破坏皮脂膜", "可能致敏"],
    goodFor: [],
    badFor: ["敏感肌", "干性肌肤", "屏障受损"],
    avoidWith: [],
  },
  {
    name: "SLES",
    nameEn: "Sodium Laureth Sulfate",
    aliases: ["月桂醇聚醚硫酸酯钠"],
    category: "清洁",
    safety: 3,
    functions: ["清洁", "起泡"],
    description: "SLS的温和版本，但仍有一定刺激性",
    concerns: ["中等刺激性"],
    goodFor: ["油性肌肤"],
    badFor: ["敏感肌"],
    avoidWith: [],
  },
  {
    name: "椰油基葡糖苷",
    nameEn: "Coco-Glucoside",
    aliases: ["APG"],
    category: "清洁",
    safety: 5,
    functions: ["温和清洁", "起泡"],
    description: "天然来源的温和表活，适合敏感肌",
    concerns: [],
    goodFor: ["敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },

  // ===== 防腐 =====
  {
    name: "苯氧乙醇",
    nameEn: "Phenoxyethanol",
    aliases: [],
    category: "防腐",
    safety: 4,
    functions: ["防腐"],
    description: "广谱防腐剂，替代传统尼泊金酯类",
    concerns: ["高浓度可能刺激"],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "苯甲酸钠",
    nameEn: "Sodium Benzoate",
    aliases: [],
    category: "防腐",
    safety: 4,
    functions: ["防腐"],
    description: "食品级防腐剂，安全性较高",
    concerns: [],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "MIT",
    nameEn: "Methylisothiazolinone",
    aliases: ["甲基异噻唑啉酮"],
    category: "防腐",
    safety: 1,
    functions: ["防腐"],
    description: "高致敏风险防腐剂，欧盟已限制驻留产品使用",
    concerns: ["高致敏风险", "接触性皮炎", "欧盟限制使用"],
    goodFor: [],
    badFor: ["敏感肌", "所有肤质"],
    avoidWith: [],
  },
  {
    name: "对羟基苯甲酸酯",
    nameEn: "Paraben",
    aliases: ["尼泊金酯", "羟苯甲酯", "羟苯丙酯", "methylparaben", "propylparaben"],
    category: "防腐",
    safety: 3,
    functions: ["防腐"],
    description: "传统防腐剂，争议较大但低浓度安全性可接受",
    concerns: ["可能干扰内分泌", "争议成分"],
    goodFor: [],
    badFor: ["敏感肌"],
    avoidWith: [],
  },

  // ===== 其他 =====
  {
    name: "酒精",
    nameEn: "Alcohol Denat.",
    aliases: ["乙醇", "变性乙醇", "alcohol"],
    category: "其他",
    safety: 3,
    functions: ["促渗透", "控油", "溶剂"],
    description: "促进成分渗透和控油，但长期高浓度使用伤害屏障",
    concerns: ["破坏皮脂膜", "加速水分蒸发", "长期使用致敏"],
    goodFor: ["油性肌肤(低浓度)"],
    badFor: ["干性肌肤", "敏感肌", "屏障受损"],
    avoidWith: ["果酸", "视黄醇"],
  },
  {
    name: "香精",
    nameEn: "Fragrance",
    aliases: ["parfum", "香料"],
    category: "其他",
    safety: 2,
    functions: ["增香"],
    description: "增加产品香味，但是常见致敏源",
    concerns: ["常见致敏源", "可能含数十种未标注化学物质"],
    goodFor: [],
    badFor: ["敏感肌"],
    avoidWith: [],
  },
  {
    name: "矿物油",
    nameEn: "Mineral Oil",
    aliases: ["液体石蜡", "凡士林", "petrolatum"],
    category: "其他",
    safety: 4,
    functions: ["封闭保湿", "润肤"],
    description: "高度精炼的封闭性保湿剂，安全但质感厚重",
    concerns: ["质感厚重", "可能闷痘"],
    goodFor: ["极干性肌肤"],
    badFor: ["油性肌肤", "痘痘肌"],
    avoidWith: [],
  },
  {
    name: "硅油",
    nameEn: "Dimethicone",
    aliases: ["聚二甲基硅氧烷", "环聚二甲基硅氧烷", "cyclomethicone"],
    category: "其他",
    safety: 4,
    functions: ["润滑", "成膜", "填充毛孔"],
    description: "赋予产品丝滑质感，形成保护膜",
    concerns: ["可能闷痘(因人而异)"],
    goodFor: ["中性肌肤"],
    badFor: ["痘痘肌(部分人)"],
    avoidWith: [],
  },
  {
    name: "色素",
    nameEn: "CI 77491",
    aliases: ["着色剂", "CI 77492", "CI 77499"],
    category: "其他",
    safety: 3,
    functions: ["着色"],
    description: "赋予产品颜色，无护肤功效",
    concerns: ["部分色素可能致敏"],
    goodFor: [],
    badFor: ["敏感肌"],
    avoidWith: [],
  },

  // ===== 补充更多成分到 80+ =====
  {
    name: "过氧化苯甲酰",
    nameEn: "Benzoyl Peroxide",
    aliases: ["BPO"],
    category: "去角质",
    safety: 3,
    functions: ["杀菌", "祛痘", "去角质"],
    description: "强效祛痘成分，杀灭痤疮丙酸杆菌",
    concerns: ["刺激性强", "漂白织物", "致干燥脱皮"],
    goodFor: ["痘痘肌"],
    badFor: ["敏感肌", "干性肌肤"],
    avoidWith: ["视黄醇", "维生素C"],
  },
  {
    name: "烟酸",
    nameEn: "Nicotinic Acid",
    aliases: ["维生素B3酸"],
    category: "美白",
    safety: 3,
    functions: ["扩张血管", "促循环"],
    description: "烟酰胺在酸性条件下的转化产物，会引起潮红",
    concerns: ["引起面部潮红", "刺痛感"],
    goodFor: [],
    badFor: ["敏感肌"],
    avoidWith: [],
  },
  {
    name: "二裂酵母发酵产物",
    nameEn: "Bifida Ferment Lysate",
    aliases: ["PITERA", "酵母精华"],
    category: "修护",
    safety: 5,
    functions: ["修护", "抗氧化", "保湿", "提亮"],
    description: "酵母发酵精华，多重修护功效的明星成分",
    concerns: [],
    goodFor: ["所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "半乳糖酵母样菌发酵产物滤液",
    nameEn: "Galactomyces Ferment Filtrate",
    aliases: ["酵母滤液", "GFF"],
    category: "修护",
    safety: 5,
    functions: ["提亮", "保湿", "控油"],
    description: "SK-II核心成分，调节肌肤新陈代谢",
    concerns: [],
    goodFor: ["所有肤质", "暗沉肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "水解胶原蛋白",
    nameEn: "Hydrolyzed Collagen",
    aliases: ["胶原蛋白"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "修护"],
    description: "小分子胶原蛋白，外用主要起保湿作用",
    concerns: ["外用无法直接补充真皮层胶原"],
    goodFor: ["干性肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "山茶花油",
    nameEn: "Camellia Japonica Seed Oil",
    aliases: ["茶花籽油"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "润肤", "抗氧化"],
    description: "富含油酸的植物油，亲肤性好滋润不油腻",
    concerns: [],
    goodFor: ["干性肌肤", "中性肌肤"],
    badFor: ["油性肌肤"],
    avoidWith: [],
  },
  {
    name: "荷荷巴油",
    nameEn: "Jojoba Oil",
    aliases: ["霍霍巴油"],
    category: "保湿",
    safety: 5,
    functions: ["保湿", "平衡油脂"],
    description: "液态蜡酯，结构接近皮脂，平衡油脂分泌",
    concerns: [],
    goodFor: ["所有肤质", "油性肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "乙基己基甘油",
    nameEn: "Ethylhexylglycerin",
    aliases: [],
    category: "防腐",
    safety: 4,
    functions: ["防腐增效", "保湿"],
    description: "辅助防腐剂，增强其他防腐剂效果",
    concerns: [],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "EDTA二钠",
    nameEn: "Disodium EDTA",
    aliases: [],
    category: "其他",
    safety: 4,
    functions: ["螯合剂", "稳定剂"],
    description: "螯合金属离子，稳定配方",
    concerns: [],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "卡波姆",
    nameEn: "Carbomer",
    aliases: [],
    category: "其他",
    safety: 5,
    functions: ["增稠", "稳定"],
    description: "常用增稠剂，赋予产品凝胶质地",
    concerns: [],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "黄原胶",
    nameEn: "Xanthan Gum",
    aliases: [],
    category: "其他",
    safety: 5,
    functions: ["增稠", "稳定"],
    description: "天然多糖增稠剂，稳定乳化体系",
    concerns: [],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "聚山梨醇酯-20",
    nameEn: "Polysorbate 20",
    aliases: ["吐温20"],
    category: "其他",
    safety: 4,
    functions: ["乳化", "增溶"],
    description: "非离子表面活性剂，帮助油水混合",
    concerns: [],
    goodFor: [],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "抗坏血酸磷酸酯镁",
    nameEn: "Magnesium Ascorbyl Phosphate",
    aliases: ["MAP", "VC磷酸酯镁"],
    category: "美白",
    safety: 5,
    functions: ["美白", "抗氧化"],
    description: "稳定型VC衍生物，温和有效不易氧化",
    concerns: [],
    goodFor: ["敏感肌", "暗沉肌肤"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "抗坏血酸葡糖苷",
    nameEn: "Ascorbyl Glucoside",
    aliases: ["AA2G", "VC糖苷"],
    category: "美白",
    safety: 5,
    functions: ["美白", "抗氧化"],
    description: "稳定型VC衍生物，在皮肤中缓慢释放活性VC",
    concerns: [],
    goodFor: ["敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "4-丁基间苯二酚",
    nameEn: "4-Butylresorcinol",
    aliases: ["377", "苯乙基间苯二酚"],
    category: "美白",
    safety: 4,
    functions: ["美白", "淡斑"],
    description: "高效酪氨酸酶抑制剂，美白效果显著",
    concerns: ["部分人可能不耐受"],
    goodFor: ["色斑肌肤", "暗沉肌肤"],
    badFor: ["敏感肌"],
    avoidWith: [],
  },
  {
    name: "视黄醇棕榈酸酯",
    nameEn: "Retinyl Palmitate",
    aliases: ["A酯", "维A酯"],
    category: "抗衰老",
    safety: 4,
    functions: ["抗衰老", "温和"],
    description: "视黄醇的温和衍生物，刺激性低但效果也较弱",
    concerns: ["效果弱于视黄醇"],
    goodFor: ["A醇入门", "敏感肌"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "HPR",
    nameEn: "Hydroxypinacolone Retinoate",
    aliases: ["羟基频哪酮视黄酸酯"],
    category: "抗衰老",
    safety: 4,
    functions: ["抗衰老", "促细胞更新"],
    description: "新型视黄醇衍生物，直接作用无需转化，刺激性低",
    concerns: [],
    goodFor: ["A醇不耐受人群", "敏感肌"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "乳糖酸",
    nameEn: "Lactobionic Acid",
    aliases: ["PHA", "葡萄糖酸内酯"],
    category: "去角质",
    safety: 5,
    functions: ["去角质", "保湿", "抗氧化"],
    description: "第三代果酸(PHA)，分子量大极其温和",
    concerns: [],
    goodFor: ["敏感肌", "所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "十一碳烯酰基苯丙氨酸",
    nameEn: "Undecylenoyl Phenylalanine",
    aliases: ["Sepiwhite MSH"],
    category: "美白",
    safety: 5,
    functions: ["美白"],
    description: "抑制α-MSH信号通路，从源头减少黑色素生成",
    concerns: [],
    goodFor: ["所有肤质"],
    badFor: [],
    avoidWith: [],
  },
  {
    name: "麦角硫因",
    nameEn: "Ergothioneine",
    aliases: ["EGT"],
    category: "抗氧化",
    safety: 5,
    functions: ["抗氧化", "抗光老化"],
    description: "蘑菇来源的超强抗氧化剂，保护线粒体DNA",
    concerns: [],
    goodFor: ["所有肤质", "光老化肌肤"],
    badFor: [],
    avoidWith: [],
  },
];

// ===== 成分匹配函数 =====
export function parseIngredientText(text: string): string[] {
  return text
    .split(/[,，、\n\/;；]+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

export function matchIngredient(name: string): IngredientInfo | null {
  const lower = name.toLowerCase().trim();
  // 1. 精确匹配中文名
  const exact = INGREDIENT_DB.find((i) => i.name === lower || i.name === name);
  if (exact) return exact;
  // 2. 精确匹配英文名
  const enExact = INGREDIENT_DB.find((i) => i.nameEn.toLowerCase() === lower);
  if (enExact) return enExact;
  // 3. 别名匹配
  const alias = INGREDIENT_DB.find((i) =>
    i.aliases.some((a) => a.toLowerCase() === lower)
  );
  if (alias) return alias;
  // 4. 包含匹配
  const contains = INGREDIENT_DB.find(
    (i) =>
      i.name.includes(name) ||
      name.includes(i.name) ||
      i.nameEn.toLowerCase().includes(lower) ||
      lower.includes(i.nameEn.toLowerCase()) ||
      i.aliases.some(
        (a) => a.toLowerCase().includes(lower) || lower.includes(a.toLowerCase())
      )
  );
  return contains || null;
}

// 安全等级颜色
export function safetyColor(level: number): string {
  if (level >= 4) return "#4A9A6B"; // 绿
  if (level >= 3) return "#C8A84E"; // 黄
  return "#C0392B"; // 红
}

export function safetyEmoji(level: number): string {
  if (level >= 4) return "🟢";
  if (level >= 3) return "🟡";
  return "🔴";
}

export function safetyLabel(level: number): string {
  if (level === 5) return "非常安全";
  if (level === 4) return "安全";
  if (level === 3) return "一般";
  if (level === 2) return "中风险";
  return "高风险";
}
